### ISSUE TITLE
Bunyan 1.3.5 crashed TypeError Object.keys called on non-object

### ISSUE THREAD

**Issue by frnk94** [trentm/node-bunyan#261] opened 2015-06-02 18:17 UTC
* platform: darwin
* node version: v0.12.3
* bunyan version: 1.3.5
* argv: ["node","/Users/francois/Documents/programation/web/solargraf/node_modules/bunyan/bin/bunyan","-o","short","-L"]
* log line: "{\"name\":\"all\",\"hostname\":\"Francoiss-MacBook-Pro.local\",\"pid\":10373,\"req_id\":\"da88716d-814c-4bfb-9c3e-ae4aa464edd3\",\"level\":30,\"remote-address\":\"127.0.0.1\",\"ip\":\"127.0.0.1\",\"method\":\"POST\",\"url\":\"/register\",\"referer\":\"http://localhost:3000/register\",\"user-agent\":{\"family\":\"Chrome\",\"major\":\"45\",\"minor\":\"0\",\"patch\":\"2418\",\"device\":{\"family\":\"Other\",\"major\":\"0\",\"minor\":\"0\",\"patch\":\"0\"},\"os\":{\"family\":\"Mac OS X\",\"major\":\"10\",\"minor\":\"10\",\"patch\":\"3\"}},\"body\":{\"name\":\"987\",\"firstname\":\"897\",\"phone\":\"897\",\"email\":\"789\",\"password\":\"8977\",\"confirmPassword\":\"987\",\"signin\":\"GET FREE TRIAL\"},\"short-body\":\"{ name: '987',\\n  fir\",\"http-version\":\"1.1\",\"response-time\":1552.205004,\"response-hrtime\":[1,552205004],\"status-code\":200,\"req-headers\":{\"host\":\"localhost:3000\",\"connection\":\"keep-alive\",\"content-length\":\"98\",\"cache-control\":\"max-age=0\",\"accept\":\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\",\"origin\":\"http://localhost:3000\",\"user-agent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2418.0 Safari/537.36\",\"content-type\":\"application/x-www-form-urlencoded\",\"referer\":\"http://localhost:3000/register\",\"accept-encoding\":\"gzip, deflate\",\"accept-language\":\"en-US,en;q=0.8,fr;q=0.6\"},\"res-headers\":{\"x-powered-by\":\"Express\"},\"req\":{\"method\":\"POST\",\"url\":\"/register\",\"headers\":\"[Circular]\"},\"res\":{\"statusCode\":200,\"header\":null},\"incoming\":\"<--\",\"msg\":\"127.0.0.1 <-- POST /register HTTP/1.1 200 - http://localhost:3000/register Chrome 45.0 Mac OS X 10.10.3 1552.205004 ms\",\"time\":\"2015-06-02T18:13:33.112Z\",\"v\":0}"
* stack:
*     TypeError: Object.keys called on non-object
*         at Function.keys (native)
*         at _res (/Users/francois/Documents/programation/web/solargraf/node_modules/bunyan/bin/bunyan:946:29)
*         at emitRecord (/Users/francois/Documents/programation/web/solargraf/node_modules/bunyan/bin/bunyan:972:13)
*         at handleLogLine (/Users/francois/Documents/programation/web/solargraf/node_modules/bunyan/bin/bunyan:723:16)
*         at Socket.<anonymous> (/Users/francois/Documents/programation/web/solargraf/node_modules/bunyan/bin/bunyan:1124:13)
*         at Socket.emit (events.js:107:17)
*         at readableAddChunk (_stream_readable.js:163:16)
*         at Socket.Readable.push (_stream_readable.js:126:10)
*         at Pipe.onread (net.js:538:20)
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:775:14)

**Comment by sonnyp** [comment] 2015-09-04 23:33
duplicate of https://github.com/trentm/node-bunyan/issues/257

**Closed** 2015-09-08 18:12 UTC
