### ISSUE TITLE
DtraceProviderBinding :: module not found error

### ISSUE THREAD

**Issue by PoonamDaxini** [trentm/node-bunyan#361] opened 2016-02-24 11:14 UTC
Attach log of npm install

```
npm verb unbuild node_modules/.staging/dtrace-provider-5e86d59d
npm verb unbuild node_modules/.staging/bindings-459adb31
npm verb gentlyRm don't care about contents; nuking /Users/Poonam/htdocs/mintoyota/api/node_modules/.staging/hiredis-6ab5f51a
npm verb unbuild node_modules/.staging/nan-049d5bfb
npm verb tar unpack /Users/Poonam/.npm/hiredis/0.4.1/package.tgz
npm verb tar unpacking to /Users/Poonam/htdocs/mintoyota/api/node_modules/.staging/hiredis-6ab5f51a
npm verb gentlyRm don't care about contents; nuking /Users/Poonam/htdocs/mintoyota/api/node_modules/.staging/hiredis-6ab5f51a
npm verb gentlyRm don't care about contents; nuking /Users/Poonam/htdocs/mintoyota/api/node_modules/.staging/dtrace-provider-5e86d59d
npm verb gentlyRm don't care about contents; nuking /Users/Poonam/htdocs/mintoyota/api/node_modules/.staging/bindings-459adb31
npm verb tar unpack /Users/Poonam/.npm/dtrace-provider/0.2.8/package.tgz
npm verb tar unpacking to /Users/Poonam/htdocs/mintoyota/api/node_modules/.staging/dtrace-provider-5e86d59d
npm verb gentlyRm don't care about contents; nuking /Users/Poonam/htdocs/mintoyota/api/node_modules/.staging/dtrace-provider-5e86d59d
npm verb tar unpack /Users/Poonam/.npm/bindings/1.2.1/package.tgz
npm verb tar unpacking to /Users/Poonam/htdocs/mintoyota/api/node_modules/.staging/bindings-459adb31
npm verb gentlyRm don't care about contents; nuking /Users/Poonam/htdocs/mintoyota/api/node_modules/.staging/bindings-459adb31
npm verb gentlyRm don't care about contents; nuking /Users/Poonam/htdocs/mintoyota/api/node_modules/.staging/nan-049d5bfb
npm verb tar unpack /Users/Poonam/.npm/nan/1.8.4/package.tgz
npm verb tar unpacking to /Users/Poonam/htdocs/mintoyota/api/node_modules/.staging/nan-049d5bfb
npm verb gentlyRm don't care about contents; nuking /Users/Poonam/htdocs/mintoyota/api/node_modules/.staging/nan-049d5bfb
npm verb gentlyRm don't care about contents; nuking /Users/Poonam/htdocs/mintoyota/api/node_modules/.staging/bindings-459adb31/node_modules
npm verb gentlyRm don't care about contents; nuking /Users/Poonam/htdocs/mintoyota/api/node_modules/.staging/nan-049d5bfb/node_modules
npm verb gentlyRm don't care about contents; nuking /Users/Poonam/htdocs/mintoyota/api/node_modules/.staging/hiredis-6ab5f51a/node_modules
npm verb gentlyRm don't care about contents; nuking /Users/Poonam/htdocs/mintoyota/api/node_modules/.staging/dtrace-provider-5e86d59d/node_modules
npm info lifecycle dtrace-provider@0.2.8~preinstall: dtrace-provider@0.2.8
npm info lifecycle bindings@1.2.1~preinstall: bindings@1.2.1
npm info lifecycle nan@1.8.4~preinstall: nan@1.8.4
npm info lifecycle hiredis@0.4.1~preinstall: hiredis@0.4.1
npm info lifecycle mv@0.0.5~preuninstall: mv@0.0.5
npm info lifecycle mv@0.0.5~uninstall: mv@0.0.5
npm verb unbuild rmStuff mv@0.0.5 from /Users/Poonam/htdocs/mintoyota/api/node_modules
npm info lifecycle mv@0.0.5~postuninstall: mv@0.0.5
npm info lifecycle mv@0.0.5~preinstall: mv@0.0.5
npm info linkStuff dtrace-provider@0.2.8
npm verb linkBins dtrace-provider@0.2.8
npm verb linkMans dtrace-provider@0.2.8
npm info linkStuff bindings@1.2.1
npm verb linkBins bindings@1.2.1
npm verb linkMans bindings@1.2.1
npm info linkStuff nan@1.8.4
npm verb linkBins nan@1.8.4
npm verb linkMans nan@1.8.4
npm info linkStuff mv@0.0.5
npm verb linkBins mv@0.0.5
npm verb linkMans mv@0.0.5
npm info linkStuff hiredis@0.4.1
npm verb linkBins hiredis@0.4.1
npm verb linkMans hiredis@0.4.1
npm info lifecycle dtrace-provider@0.2.8~install: dtrace-provider@0.2.8

> dtrace-provider@0.2.8 install /Users/Poonam/htdocs/mintoyota/api/node_modules/dtrace-provider
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.2.1
gyp info using node@5.6.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:78:19)
gyp verb `which` failed     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:87:29)
gyp verb `which` failed     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:98:16
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:82:15)
gyp verb `which` failed  python2 [Error: not found: python2]
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 5.6.0
gyp verb command install [ '5.6.0' ]
gyp verb install input version string "5.6.0"
gyp verb install installing version: 5.6.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 5.6.0
gyp verb build dir attempting to create "build" dir: /Users/Poonam/htdocs/mintoyota/api/node_modules/dtrace-provider/build
gyp verb build dir "build" dir needed to be created? /Users/Poonam/htdocs/mintoyota/api/node_modules/dtrace-provider/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/Poonam/htdocs/mintoyota/api/node_modules/dtrace-provider/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/Poonam/htdocs/mintoyota/api/node_modules/dtrace-provider/config.gypi
gyp verb common.gypi checking for gypi file: /Users/Poonam/htdocs/mintoyota/api/node_modules/dtrace-provider/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Poonam/htdocs/mintoyota/api/node_modules/dtrace-provider/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Poonam/.node-gyp/5.6.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/Poonam/.node-gyp/5.6.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/Poonam/htdocs/mintoyota/api/node_modules/dtrace-provider',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/Poonam/.node-gyp/5.6.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  LD_LIBRARY_PATH=/Users/Poonam/htdocs/mintoyota/api/node_modules/dtrace-provider/build/Release/lib.host:/Users/Poonam/htdocs/mintoyota/api/node_modules/dtrace-provider/build/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../.; sh libusdt-build.sh
Building libusdt for x86_64
not found: gmake
rm -f *.gch
rm -f *.o
rm -f libusdt.a
rm -f test_usdt
rm -f test_usdt32
rm -f test_usdt64
rm -f test_mem_usage
gcc -O2 -arch x86_64   -c -o usdt.o usdt.c
usdt.c:212:9: warning: implicit declaration of function 'usdt_dof_section_free' is invalid in C99 [-Wimplicit-function-declaration]
        usdt_dof_section_free(&strtab);
        ^
usdt.c:238:9: warning: implicit declaration of function 'usdt_dof_file_free' is invalid in C99 [-Wimplicit-function-declaration]
        usdt_dof_file_free(provider->file);
        ^
2 warnings generated.
gcc -O2 -arch x86_64   -c -o usdt_dof_file.o usdt_dof_file.c
gcc -arch x86_64 -o usdt_tracepoints.o -c usdt_tracepoints_x86_64.s
gcc -O2 -arch x86_64   -c -o usdt_probe.o usdt_probe.c
gcc -O2 -arch x86_64   -c -o usdt_dof.o usdt_dof.c
gcc -O2 -arch x86_64   -c -o usdt_dof_sections.o usdt_dof_sections.c
rm -f libusdt.a
ar cru libusdt.a usdt.o usdt_dof_file.o usdt_tracepoints.o usdt_probe.o usdt_dof.o usdt_dof_sections.o
ranlib libusdt.a
  touch Release/obj.target/libusdt.stamp
  c++ '-DNODE_GYP_MODULE_NAME=DTraceProviderBindings' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/Poonam/.node-gyp/5.6.0/include/node -I/Users/Poonam/.node-gyp/5.6.0/src -I/Users/Poonam/.node-gyp/5.6.0/deps/uv/include -I/Users/Poonam/.node-gyp/5.6.0/deps/v8/include -I../libusdt  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/DTraceProviderBindings/dtrace_provider.o.d.raw   -c -o Release/obj.target/DTraceProviderBindings/dtrace_provider.o ../dtrace_provider.cc
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:69:44: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                           ^~~~~~~~~~~~~
                                           v8::internal::Arguments
/Users/Poonam/.node-gyp/5.6.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:70:45: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static v8::Handle<v8::Value> Fire(const v8::Arguments& args);
                                            ^~~~~~~~~~~~~
                                            v8::internal::Arguments
/Users/Poonam/.node-gyp/5.6.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:87:44: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                           ^~~~~~~~~~~~~
                                           v8::internal::Arguments
/Users/Poonam/.node-gyp/5.6.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:88:49: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static v8::Handle<v8::Value> AddProbe(const v8::Arguments& args);
                                                ^~~~~~~~~~~~~
                                                v8::internal::Arguments
/Users/Poonam/.node-gyp/5.6.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:89:52: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static v8::Handle<v8::Value> RemoveProbe(const v8::Arguments& args);
                                                   ^~~~~~~~~~~~~
                                                   v8::internal::Arguments
/Users/Poonam/.node-gyp/5.6.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:90:47: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static v8::Handle<v8::Value> Enable(const v8::Arguments& args);
                                              ^~~~~~~~~~~~~
                                              v8::internal::Arguments
/Users/Poonam/.node-gyp/5.6.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:91:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static v8::Handle<v8::Value> Disable(const v8::Arguments& args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments
/Users/Poonam/.node-gyp/5.6.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:92:45: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    static v8::Handle<v8::Value> Fire(const v8::Arguments& args);
                                            ^~~~~~~~~~~~~
                                            v8::internal::Arguments
/Users/Poonam/.node-gyp/5.6.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../dtrace_provider.cc:23:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/Poonam/.node-gyp/5.6.0/include/node/v8.h:889:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../dtrace_provider.cc:25:55: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'v8::Handle<v8::Value> (const v8::internal::Arguments &)'
    Local<FunctionTemplate> t = FunctionTemplate::New(DTraceProvider::New);
                                                      ^~~~~~~~~~~~~~~~~~~
/Users/Poonam/.node-gyp/5.6.0/include/node/v8.h:4349:16: note: passing argument to parameter 'isolate' here
      Isolate* isolate, FunctionCallback callback = 0,
               ^
../dtrace_provider.cc:26:58: error: 'New' is a private member of 'v8::PersistentBase<v8::FunctionTemplate>'
    constructor_template = Persistent<FunctionTemplate>::New(t);
                                                         ^
/Users/Poonam/.node-gyp/5.6.0/include/node/v8.h:643:23: note: declared private here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
../dtrace_provider.cc:26:28: error: too few arguments to function call, expected 2, have 1; did you mean 'DTraceProbe::New'?
    constructor_template = Persistent<FunctionTemplate>::New(t);
                           ^~~~~~~~~~
                           DTraceProbe::New
../dtrace_provider.h:69:34: note: 'DTraceProbe::New' declared here
    static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                 ^
../dtrace_provider.cc:27:25: error: member reference type 'Persistent<v8::FunctionTemplate>' is not a pointer; maybe you meant to use '.'?
    constructor_template->InstanceTemplate()->SetInternalFieldCount(1);
    ~~~~~~~~~~~~~~~~~~~~^~
                        .
../dtrace_provider.cc:27:27: error: no member named 'InstanceTemplate' in 'v8::Persistent<v8::FunctionTemplate, v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
    constructor_template->InstanceTemplate()->SetInternalFieldCount(1);
    ~~~~~~~~~~~~~~~~~~~~  ^
../dtrace_provider.cc:28:25: error: member reference type 'Persistent<v8::FunctionTemplate>' is not a pointer; maybe you meant to use '.'?
    constructor_template->SetClassName(String::NewSymbol("DTraceProvider"));
    ~~~~~~~~~~~~~~~~~~~~^~
                        .
../dtrace_provider.cc:28:27: error: no member named 'SetClassName' in 'v8::Persistent<v8::FunctionTemplate, v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
    constructor_template->SetClassName(String::NewSymbol("DTraceProvider"));
    ~~~~~~~~~~~~~~~~~~~~  ^
../dtrace_provider.cc:28:48: error: no member named 'NewSymbol' in 'v8::String'
    constructor_template->SetClassName(String::NewSymbol("DTraceProvider"));
                                       ~~~~~~~~^
../dtrace_provider.cc:30:31: error: no viable conversion from 'Persistent<v8::FunctionTemplate>' to 'v8::Local<v8::FunctionTemplate>'
    NODE_SET_PROTOTYPE_METHOD(constructor_template, "addProbe", DTraceProvider::AddProbe);
                              ^~~~~~~~~~~~~~~~~~~~
/Users/Poonam/.node-gyp/5.6.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'Persistent<v8::FunctionTemplate>' to 'const v8::Local<v8::FunctionTemplate> &' for 1st argument
class Local {
      ^
/Users/Poonam/.node-gyp/5.6.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'Persistent<v8::FunctionTemplate>' to 'v8::Local<v8::FunctionTemplate> &&' for 1st argument
class Local {
      ^
/Users/Poonam/.node-gyp/5.6.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'Persistent'
  V8_INLINE Local(Local<S> that)
            ^
/Users/Poonam/.node-gyp/5.6.0/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'Persistent<v8::FunctionTemplate>'
  V8_INLINE Local(S* that)
            ^
/Users/Poonam/.node-gyp/5.6.0/include/node/node.h:252:71: note: passing argument to parameter 'recv' here
inline void NODE_SET_PROTOTYPE_METHOD(v8::Local<v8::FunctionTemplate> recv,
                                                                      ^
../dtrace_provider.cc:31:31: error: no viable conversion from 'Persistent<v8::FunctionTemplate>' to 'v8::Local<v8::FunctionTemplate>'
    NODE_SET_PROTOTYPE_METHOD(constructor_template, "removeProbe", DTraceProvider::RemoveProbe);
                              ^~~~~~~~~~~~~~~~~~~~
/Users/Poonam/.node-gyp/5.6.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'Persistent<v8::FunctionTemplate>' to 'const v8::Local<v8::FunctionTemplate> &' for 1st argument
class Local {
      ^
/Users/Poonam/.node-gyp/5.6.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'Persistent<v8::FunctionTemplate>' to 'v8::Local<v8::FunctionTemplate> &&' for 1st argument
class Local {
      ^
/Users/Poonam/.node-gyp/5.6.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'Persistent'
  V8_INLINE Local(Local<S> that)
            ^
/Users/Poonam/.node-gyp/5.6.0/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'Persistent<v8::FunctionTemplate>'
  V8_INLINE Local(S* that)
            ^
/Users/Poonam/.node-gyp/5.6.0/include/node/node.h:252:71: note: passing argument to parameter 'recv' here
inline void NODE_SET_PROTOTYPE_METHOD(v8::Local<v8::FunctionTemplate> recv,
                                                                      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/DTraceProviderBindings/dtrace_provider.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Poonam/htdocs/mintoyota/api/node_modules/dtrace-provider
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm verb lifecycle dtrace-provider@0.2.8~install: unsafe-perm in lifecycle true
npm verb lifecycle dtrace-provider@0.2.8~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Poonam/htdocs/mintoyota/api/node_modules/dtrace-provider/node_modules/.bin:/Users/Poonam/htdocs/mintoyota/api/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mysql/bin
npm verb lifecycle dtrace-provider@0.2.8~install: CWD: /Users/Poonam/htdocs/mintoyota/api/node_modules/dtrace-provider
npm info lifecycle dtrace-provider@0.2.8~install: Failed to exec install script
npm WARN install:dtrace-provider@0.2.8 dtrace-provider@0.2.8 install: `node-gyp rebuild`
npm WARN install:dtrace-provider@0.2.8 Exit status 1
npm verb install:dtrace-provider@0.2.8 Error: dtrace-provider@0.2.8 install: `node-gyp rebuild`
npm verb install:dtrace-provider@0.2.8 Exit status 1
npm verb install:dtrace-provider@0.2.8     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
npm verb install:dtrace-provider@0.2.8     at emitTwo (events.js:100:13)
npm verb install:dtrace-provider@0.2.8     at EventEmitter.emit (events.js:185:7)
npm verb install:dtrace-provider@0.2.8     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb install:dtrace-provider@0.2.8     at emitTwo (events.js:100:13)
npm verb install:dtrace-provider@0.2.8     at ChildProcess.emit (events.js:185:7)
npm verb install:dtrace-provider@0.2.8     at maybeClose (internal/child_process.js:827:16)
npm verb install:dtrace-provider@0.2.8     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm info lifecycle bindings@1.2.1~install: bindings@1.2.1
npm info lifecycle nan@1.8.4~install: nan@1.8.4
npm info lifecycle mv@0.0.5~install: mv@0.0.5
npm info lifecycle hiredis@0.4.1~install: hiredis@0.4.1

> hiredis@0.4.1 install /Users/Poonam/htdocs/mintoyota/api/node_modules/hiredis
> node-gyp rebuild
```

`

on running file I get this error 

```
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
```

**Comment by unsalted** [comment] 2016-02-28 04:33
+1

**Comment by bennybennet** [comment] 2016-02-29 19:03
+1 

workaround in my case:
```
rm -rf node_modules/
npm install 
```

**Comment by mmocny** [comment] 2016-03-04 20:02
I've just found that this is caused by using v0.5 of dtrace-provider, and that upgrading to v0.6 resolves the  issue.

I'm not sure why, but this can be resolved by updating your package.json.  Also curious, why is dtrace-provider both a dependency *and* an optionalDependency?

Thanks!

**Comment by trentm** [comment] 2016-03-28 18:03
@PoonamDaxini Do you know why version 0.2.8 of dtrace-provider is being installed in your npm install log? Current Bunyan has this optional dep:

```
"optionalDependencies": {
    "dtrace-provider": "~0.6",
```

which should tell `npm install` to use version 0.6.

>  Also curious, why is dtrace-provider both a dependency and an optionalDependency?

@mmocny That isn't the case. It is an optionalDependency only (https://github.com/trentm/node-bunyan/blob/ffc6355b6fc7af7faaffcfc35c86c6f76f5cec96/package.json#L23).  I have a *comment* in package.json saying why dtrace-provider is listed as an optional dep (https://github.com/trentm/node-bunyan/blob/ffc6355b6fc7af7faaffcfc35c86c6f76f5cec96/package.json#L19). "dependencies" is empty (https://github.com/trentm/node-bunyan/blob/ffc6355b6fc7af7faaffcfc35c86c6f76f5cec96/package.json#L38-L39).

**Comment by misterinterrupt** [comment] 2016-12-02 23:22
can/should this become a peer dependency?

**Closed** 2016-12-02 23:42 UTC
