### ISSUE TITLE
Bunyan 1.7.1 crashed: TypeError: Cannot read property 'pipe' of null

### ISSUE THREAD

**Issue by ajitprak** [trentm/node-bunyan#371] opened 2016-03-15 12:36 UTC
I am trying change log levels dynamically using bunyan dtrace, It was working fine for older versions of node, After taking the latest node update 4.4.0, I am getting the above error when I run the command sudo bunyan -p *. Please help me.

**Comment by oliverdunk** [comment] 2016-03-16 22:35
Can confirm, could someone take a look at this perhaps?

**Comment by trentm** [comment] 2016-03-17 05:29
duplicate of #370

**Closed by trentm** 2016-03-17 05:29 UTC
Labels: Component-CLI, Resolution-Duplicate, Type-Bug
