### ISSUE TITLE
How to limit a logger to print only 'debug' level?

### ISSUE THREAD

**Issue by thalesfsp** [trentm/node-bunyan#339] opened 2016-01-25 21:33 UTC
Given

```js
logger.fatal('report fatal');
logger.error('report error');
logger.warn('report warn');
logger.info('report info');
logger.debug('report debug');
logger.trace('report trace');
```

Only print to stdout `logger.debug` and ignore the others

**Comment by thalesfsp** [comment] 2016-01-29 05:12
@trentm ?

**Comment by rooftopsparrow** [comment] 2016-01-29 23:06
This is a duplicate of multiple issues ( see #334, #320, and others ).

The short answer is that this works as intended and the log level is a **minimum** log level not an **exclusive** log level. The long answer is if you want that desired behavior you would need to implement you're own stream to do so with a `raw` stream.

Hope this helps!

**Closed** 2016-01-30 00:11 UTC
Labels: Component-Lib, needstriage, Type-Question
