### ISSUE TITLE
Can't rotate file sometimes for the 'rotating-file' stream type

### ISSUE THREAD

**Issue by lijjhaha** [trentm/node-bunyan#333] opened 2016-01-19 00:52 UTC
When using the stream type:'rotating-file',  the log file can't be rotated sometimes. This happens randomly.
-----------------------------------
##TestCode:
-----------------------------------
var bunyan= require('./bunyan');
var Log = bunyan.createLogger({
		src: true,
		name : 'UniSIMS',
        streams: [
            {
				type : 'rotating-file',
				level : 'info',
				path : './log_info.log',                          
				//period : '1d', // daily rotation
				period : '20000ms', // daily rotation
				count : 3 // keep 3 back copies
            }/*,
			{
				level: 'info',
                stream: process.stdout	
			}*/
        ]
	});

var count = 0;
setInterval(function(){
	count++;
	console.log('-----------------     ' + count + '                     ');
	log.info('-----------------     ' + count + '                     ');
	//log.error('-----------------     ' + count + '                     ');
},1000)
-----------------------------------
##Reason:
-----------------------------------
RotatingFileStream.prototype.rotate = function rotate() {
    // XXX What about shutdown?
    var self = this;
    var _DEBUG = false;

    // If rotation period is > ~25 days, we have to break into multiple
    // setTimeout's. See <https://github.com/joyent/node/issues/8656>.
    *if (self.rotAt && self.rotAt > Date.now()) {*
        return self._setupNextRot();
    }

 Because the NODE.JS TIMTER is inaccurate, the value of 'roaAt' maybe be still less than Data.now when the timer is called. If so, this cycyle the logger will not be rotated.
This happens randomly, but maybe serious. In some case, the logger file can continue to grow without being rotated, and reaches a large size.

**Comment by Rcomian** [comment] 2016-02-21 21:07
If you need a fix for this right now, my rotating file stream component should handle this case:

[https://www.npmjs.com/package/bunyan-rotating-file-stream](https://www.npmjs.com/package/bunyan-rotating-file-stream)

**Comment by trentm** [comment] 2016-02-29 05:49
Calling this a duplicate of #344 (instead of the other way round).  THis should be fixed in https://github.com/trentm/node-bunyan/commit/d9c5970be21a7db09607fd88eaf4bffdd9b62fbe

**Closed by trentm** 2016-02-29 05:49 UTC
Labels: Component-LibRotation, needstriage, Type-Bug
